#!/bin/bash

suffixes="h hpp c cpp"
directories="."

optstring=":s:d:"
while getopts $optstring opt ; do
    case $opt in
        s)  suffixes=$OPTARG ;;
        d)  directories=$OPTARG ;;
    esac
done            

for dir in $(tr " " " " <<< $directories) ; do
    for suffix in $(tr " " " " <<< $suffixes) ; do
	    find $dir -name "*.$suffix"
    done
done | ebrowse
